#!/bin/sh
# Author: kspice

initializeANSI()
{
  esc=""

  blackf="${esc}[30m";   redf="${esc}[31m";    greenf="${esc}[32m"
  yellowf="${esc}[33m"   bluef="${esc}[34m";   purplef="${esc}[35m"
  cyanf="${esc}[36m";    whitef="${esc}[37m"
  orangef="${esc}[38;5;208m"  # Added orange color variable

  blackb="${esc}[40m";   redb="${esc}[41m";    greenb="${esc}[42m"
  yellowb="${esc}[43m"   blueb="${esc}[44m";   purpleb="${esc}[45m"
  cyanb="${esc}[46m";    whiteb="${esc}[47m"
  orangeb="${esc}[48;5;208m"  # Added orange color variable

  boldon="${esc}[1m";    boldoff="${esc}[22m"
  italicson="${esc}[3m"; italicsoff="${esc}[23m"
  ulon="${esc}[4m";      uloff="${esc}[24m"
  invon="${esc}[7m";     invoff="${esc}[27m"

  darkbluef="${esc}[38;5;18m"   # Added dark blue foreground
  darkblueb="${esc}[48;5;18m"   # Added dark blue background

  reset="${esc}[0m"
}

initializeANSI

cat << EOF

${boldon}${yellowf}      ▄██████▄             ${reset}
${boldon}${yellowf}     ███${boldon}${whitef}▀█${boldon}${yellowf}█████            ${reset}
${boldon}${orangef}  ████${reset}${boldon}${yellowf}█████████           ${reset}
${boldon}${yellowf}     ████████▀       ▄█   ${reset}
${boldon}${yellowf}       █████        ▄██   ____             _    _   ${reset}
${boldon}${yellowf}   ▄███████████████████  |  _ \ ___   ___ | | _(_) ___ ${reset}
${boldon}${yellowf}  █████████████████████  | |_) / _ \ / _ \| |/ / |/ _ \\ ${reset}
${boldon}${yellowf}  ███████████████████▀   |  __/ (_) | (_) |   <| |  __/ ${reset}
${boldon}${yellowf}   ▀████████████████▀    |_|   \___/ \___/|_|\_\_|\___|  ${reset}
${boldon}${darkbluef}▀███████████████████████████████████████████████████████▀${reset}


EOF
